spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lujinlong007/config-repo.git
          force-pull: true #强制拉取资源文件
          #search-paths: abc,def*,
server:
  port: 60005