spring:
  application:
    name: config-bus-server
  rabbitmq:
    host: micro
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lujinlong007/config-repo.git
          force-pull: true #强制拉取资源文件
          #search-paths: abc,def*,
server:
  port: 60002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
